### ISSUE TITLE
bug 1349039 - what's new issue with locale `nb-NO` / `no-NO`

### ISSUE THREAD

**Issue by escapewindow** [mozilla-releng/mozapkpublisher#21]
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/androidpublisher/v2/applications/org.mozilla.firefox_beta/edits/08866837873297372373:commit?alt=json returned "Tried to set recent changes text for APK version 2015477249 for language no-NO. Language is not associated with the app.">
exit code: 1

I see https://l10n.mozilla-community.org/stores_l10n/api/v1/google/localesmapping/?reverse maps our `nb-NO` to gplay's `no-NO`.  I also see we map those [here](https://github.com/mozilla-releng/mozapkpublisher/blob/master/mozapkpublisher/store_l10n.py#L26-L34).

To fix, we either need to:
- keep track of both locale names and update the apk with our locale name and the store with their locale name (google play may or may not allow this), OR
- add a flag into the l10n process + l10n-changesets.json to specify we should repack locale `nb-NO` as locale `no-NO`.  Since the multilocale build needs the `nb-NO` name to know which repo to pull from, we need some build/repack magic to repack this under a different name, so the apk shows `no-NO` and we don't have to do any translating during push time.

A shorter term solution might be to skip what's new changes altogether, or for the inconsistent locales.

**Comment by escapewindow** [comment]
We seem to have hit this in https://github.com/mozilla-l10n/stores_l10n/issues/105 and https://github.com/mozilla-l10n/stores_l10n/issues/43

**Comment by flodolo** [comment]
CC @delphine

One thing that isn't completely clear: is it failing only for whatsnew, or also for the main listing?
If it's the former, code should be reworked to allow failures on whatsnew.

At this point we have the problem for es-MX and nb-NO: Play Store freaks out because we're trying to update a language that is not available inside the apk. Changing locale code while repacking seems interesting, but also scary (is the internal locale switcher going to break?). 

If we could get a contact in Google to understand if we can work around this issue on the API it would be a good first step.

**Comment by JohanLorenzo** [comment]
`push_apk.py` only changes whatsnew. I agree we can report that issue as a warning. Because tasks will report as green, I'm afraid we forget about these issues at some point.

If @escapewindow thinks the build time solution is not too scary we can go with that solution. Otherwise, I'm thinking of another way: how about we take the whatsnew update out in another job?

This will allow to:

* publish the APKs even if a locale doesn't fail
* explicitly fail in the release taskgraph, if one locale becomes problematic.

That's not a trivial change, though. If we want to implement this, we'd have to:

* Allow pushapk_scriptworker to support another type of task
* Update the release graph to insert a new task after the push-apk one.
* Export (as an artifact) the version code uploaded so that new task knows what version code to change.
* Move the whatsnew update out of push_apk.py into its own script. 
* Change scriptworker to support the new type of task.

Regarding the Google contact. As this is not the first time that proposal comes up, I think we need to assign somebody on this. @flodolo Do you think that's something the l10n team should handle? Or should it belong to releng?

**Comment by flodolo** [comment]
> @flodolo, do you think that's something the l10n team should handle? Or should it belong to releng?

I think it's more on releng, since you also need to test and apply a fix (assuming there's one) to the current usage of Play Store APIs. Eventually it's a discussion to have with @delphine.

We're also looking into using this API to publish Focus for Android, so it might be worth looking for a long term solution that doesn't require the locale to be present in the .apk

**Comment by escapewindow** [comment]
> If @escapewindow thinks the build time solution is not too scary we can go with that solution. 

I'm thinking it's moderately scary, and needs a non-trivial amount of time to test to see if it's even possible.  But if it works, it might solve this type of problem for good.

> Otherwise, I'm thinking of another way: how about we take the whatsnew update out in another job?

Sure, or make it a warning as suggested above, or something like that.

**Comment by JohanLorenzo** [comment]
Closed by #22
