### ISSUE TITLE
partial rollout shouldn't set status to completed

### ISSUE THREAD

**Issue by jcristau** [mozilla-releng/mozapkpublisher#220]
I believe this is a regression from moving to the google play publishing API v3.  Instead of using a "rollout" track, partial rollouts can now be done on any track (typically "production"), but the status needs to be set appropriately.

https://developers.google.com/android-publisher/tracks#staged_rollouts
https://developers.google.com/android-publisher/api-ref/edits/tracks#resource

**Comment by jcristau** [comment]
(I pushed a commit to my repo that I think may address this, but needs review and fixing tests)

**Comment by mitchhentges** [comment]
Hmm, Google's docs aren't the best here, because the official ["APKs and Tracks" docs](https://developers.google.com/android-publisher/tracks#staged_rollouts) just mention that staged rollouts are only relevant for `production`:

> Once you have released the staged rollout version, you can gradually increase the number of users who get that version of the app, until you finally deploy that version as the "production" version.

However, the [V3 announcement](https://android-developers.googleblog.com/2019/03/changes-to-google-play-developer-api.html) notes that:

> we introduced version 3 of the API, which allows you to transactionally start, manage, and halt staged releases on all tracks, through production, open testing, closed testing (including the new additional testing tracks), and internal testing. 

Additionally, they don't explicitly mention that `track='rollout'` isn't valid any more, but I think it's smart to do the same thing as your patch and just specify `production` deliberately.

I'm grafting your patch and adding tests right now

**Comment by mitchhentges** [comment]
My PR no longer throws an error, but Google is ignoring any rollout "edit" right now :thinking: 
Rollout has stopped working since we changed to use the V3 API. Digging into this, we look like we're providing the right JSON properties, so I'm not sure what might be going wrong.

There's a [`jenkins` plugin](https://github.com/jenkinsci/google-play-android-publisher-plugin) that allegedly has V3 support, so _hopefully_ this issue is on our end. We're using a python SDK for talking to Google Play, maybe that's hiding a problem? Tomorrow I'm going to make the edit via HTTP by hand to see if I can still reproduce it.

**Comment by mitchhentges** [comment]
Using the HTTP API, I was able to successfully make a "rollout" release. This means that there's either something wrong with our automation, or the `google-api-python-client` we're using. I'm going to do some testing with the python client to see if I can make it behave.
Worst comes to worst, we can just use the HTTP API instead.

-----

Details on how I got rollout to work with the HTTP API:
1. POST https://oauth2.googleapis.com/token?grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer&assertion=...
	* Run `mozapkpublisher` and steal `assertion` from the body of `client.py:_do_refresh_request`
2. POST https://www.googleapis.com/androidpublisher/v3/applications/org.mozilla.reference.browser/edits
	* `Authorization`: `Bearer ${access_token from oauth2 request}`
3. POST https://www.googleapis.com/upload/androidpublisher/v3/applications/org.mozilla.reference.browser/edits/${editId}/apks?uploadType=media
	* `Content-Type`: `application/octet-stream`
	* Do this request once for each APK
4. PUT https://www.googleapis.com/androidpublisher/v3/applications/org.mozilla.reference.browser/edits/${editId}/tracks/nightly
	* `Content-Type`: `application/json`
```
{
    "releases": [{
        "status": "inProgress",
        "userFraction": 0.01,
        "versionCodes": [
            "12402118", <-- replace these version codes with the ones from the APKs that were uploaded
            "12402119",
            "12402120",
            "12402121"
        ]
    }]
}
```
5. POST https://www.googleapis.com/androidpublisher/v3/applications/org.mozilla.reference.browser/edits/${editId}:validate
6. POST https://www.googleapis.com/androidpublisher/v3/applications/org.mozilla.reference.browser/edits/${editId}:commit
